# YAML file for a GitHub Actions workflow to Keep The Server Running

name: Keep Render Servers Awake

on:
  schedule:
    - cron: '25 8-23 * * *'  # Runs the server at 25 minutes past the hour between 8 am and 11 pm
    - cron: '30 8-23 * * *'  # Runs the server at 30 minutes past the hour between 8 am and 11 pm
    - cron: '30 8-23 * * *'  # Runs the server at 30 minutes past the hour between 8 am and 11 pm 
    - cron: '30 8-23 * * *'  # Runs the server at 30 minutes past the hour between 8 am and 11 pm 

jobs:
  keep-awake-server1:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Keep Awake
        run: curl -s -I https://football-player-charts-stats-api.onrender.com/

  keep-awake-server2:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Keep Awake
        run: curl -s -I https://football-players-charts.onrender.com/

  keep-awake-server3:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Keep Awake
        run: curl -s -I https://tomasgarrido.onrender.com/

  keep-awake-server4:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Keep Awake
        run: curl -s -I https://ruins-of-versailles-7rbc.onrender.com/            
